language: go

go:
    - 1.8

install:
    - go get github.com/mattn/goveralls

script:
    - go get -t ./...
    - diff <(echo -n) <(gofmt -s -d .)
    - goveralls -service=travis-ci
    - go test -v -cover ./...
